
<?php

 function idiomz($cnt)
			{
$f = array(
'a bit|a little',
'a little|a bit',
'a built|built',
'built|a built',
'a great deal of|a lot',
'a lot|a great deal of',
'a great number of|a lot',
'a lot|a great number of',
'a little bit|a little',
'a little|a little bit',
'a little more|a little',
'a little|a little more',
'a long time ago|before',
'before|a long time ago',
'a lot of|a lot',
'a lot|a lot of',
'a lot of egg|confusion',
'confusion|a lot of egg',
'a very|the same',
'the same|a very',
'about as complete as|as well as',
'as well as|about as complete as',
'about now|how',
'how|about now',
'about then|around the time of',
'around the time of|about then',
'about where|about where',
'about where|about where',
'about face|round',
'round|about face',
'above all|above all',
'above all|above all',
'above ground|alive',
'alive|above ground',
'above board|honestly',
'honestly|above board',
'accord a heartly welcom|have a warm welcome',
'have a warm welcome|accord a heartly welcom',
'account for by|explained',
'explained|account for by',
'account for over|to answer more than',
'to answer more than|account for over',
'across the board|for all',
'for all|across the board',
'act amiss|err',
'err|act amiss',
'act for|to replace',
'to replace|act for',
'act like|to behave as / if',
'to behave as / if|act like',
'add fuel to the flame|to add fuel to the fire',
'to add fuel to the fire|add fuel to the flame',
'add on|add',
'add|add on',
'addressing the issues|to discuss',
'to discuss|addressing the issues',
'admission test|Entrance Examination',
'Entrance Examination|admission test',
'advanse guard|Avant-Garde',
'Avant-Garde|advanse guard',
'affected by cold|cold',
'cold|affected by cold',
'after a fashion of|in some way',
'in some way|after a fashion of',
'after a short time|soon',
'soon|after a short time',
'after all|in the end',
'in the end|after all',
'after game|otygrysh',
'otygrysh|after game',
'against the face of|on the opposite side',
'on the opposite side|against the face of',
'against time|within the established time',
'within the established time|against time',
'ahead of time|in advance',
'in advance|ahead of time',
'aim high|aim high',
'aim high|aim high',
'alarm clock|alarm clock',
'alarm clock|alarm clock',
'all alone|one',
'one|all alone',
'all along|all the time',
'all the time|all along',
'all around|completely',
'completely|all around',
'all at once|at once',
'at once|all at once',
'all but|almost',
'almost|all but',
'all for nothing|in vain',
'in vain|all for nothing',
'all in all|in general',
'in general|all in all',
'all of a sudden|suddenly',
'suddenly|all of a sudden',
'all out|total',
'total|all out',
'all over|everywhere',
'everywhere|all over',
'all over again|again',
'again|all over again',
'all right|well',
'well|all right',
'all the better|the better',
'the better|all the better',
'all the more|the more',
'the more|all the more',
'all the same|Yet',
'Yet|all the same',
'along the lines|in the direction of',
'in the direction of|along the lines',
'along with|along with',
'along with|along with',
'and no mistake|no doubt',
'no doubt|and no mistake',
'and so forth|and so on',
'and so on|and so forth',
'and so on|and so on',
'and so on|and so on',
'and the like|and so on',
'and so on|and the like',
'any longer|no longer',
'no longer|any longer',
'any more|more',
'more|any more',
'any of|any of the',
'any of the|any of',
'any one|any',
'any|any one',
'any time|at any time',
'at any time|any time',
'apple of discord|an apple of discord',
'an apple of discord|apple of discord',
'apply for|Seek',
'Seek|apply for',
'around the clock|around the clock',
'around the clock|around the clock',
'around the world|everywhere, international',
'everywhere, international|around the world',
'as a matter of fact|in fact,',
'in fact,|as a matter of fact',
'as against|compared to',
'compared to|as against',
'as early as|yet',
'yet|as early as',
'as far as|how',
'how|as far as',
'as for the|with respect',
'with respect|as for the',
'as from|ranging from',
'ranging from|as from',
'as if|as if',
'as if|as if',
'as is also|as well as',
'as well as|as is also',
'as it does|as is',
'as is|as it does',
'as late as|just',
'just|as late as',
'as likely as not|it is very likely',
'it is very likely|as likely as not',
'as little as|of all',
'of all|as little as',
'as many as|until',
'until|as many as',
'as much as|how',
'how|as much as',
'as of|according to',
'according to|as of',
'as often as not|often',
'often|as often as not',
'as regards|with respect',
'with respect|as regards',
'as to who|for example, who',
'for example, who|as to who',
'as well|also',
'as what|what',
'what|as what',
'as with|as',
'as|as with',
'as yet|yet',
'yet|as yet',
'at a blow|one stroke',
'one stroke|at a blow',
'at a glance|at a glance',
'at a glance|at a glance',
'at a guess|about',
'about|at a guess',
'at a rate of|at',
'at|at a rate of',
'at a time|at a time',
'at a time|at a time',
'at all|just',
'just|at all',
'at all points|in all respects',
'in all respects|at all points',
'at any cost|in whatever was',
'in whatever was|at any cost',
'at any hand|in any case',
'in any case|at any hand',
'at best|at best',
'at best|at best',
'at first|first',
'first|at first',
'at hand|immediately',
'immediately|at hand',
'at last|finally',
'finally|at last',
'at least|at least',
'at least|at least',
'at most|the highest',
'the highest|at most',
'at once|at once',
'at once|at once',
'at the end|eventually',
'eventually|at the end',
'at the time|at a time',
'at a time|at the time',
'at will|on request',
'on request|at will',
'back along the|behind',
'behind|back along the',
'back and forth|back and forth',
'back and forth|back and forth',
'back away|to recede, back',
'to recede, back|back away',
'back down|to depart',
'to depart|back down',
'back into|again',
'again|back into',
'back off|to give',
'to give|back off',
'back out|shy away',
'shy away|back out',
'back talk|opposition',
'opposition|back talk',
'back up|to support',
'to support|back up',
'bad cold|heavy cold',
'heavy cold|bad cold',
'bad to worse|worse and worse',
'worse and worse|bad to worse',
'baker dozen|bakers dozen',
'bakers dozen|baker dozen',
'balance out|to neutralize',
'to neutralize|balance out',
'bald apot|lysina',
'lysina|bald apot',
'ball park|Stadium',
'Stadium|ball park',
'be about to|meet',
'meet|be about to',
'be at pains|try',
'try|be at pains',
'be back|back, back',
'back, back|be back',
'be for use|designed for',
'designed for|be for use',
'be half way between|lie between',
'lie between|be half way between',
'be in effect|to be valid',
'to be valid|be in effect',
'be in error|err',
'err|be in error',
'be in place|to do',
'to do|be in place',
'be off|leave, leave',
'leave, leave|be off',
'be off by|differ on',
'differ on|be off by',
'be on the make|continue to work',
'continue to work|be on the make',
'be out to|meet',
'meet|be out to',
'beat back|reflect',
'reflect|beat back',
'beat off|beat',
'beat|beat off',
'beat up|beat',
'beat|beat up',
'beef up|to strengthen, to increase',
'to strengthen, to increase|beef up',
'bell and whistle|thingamy',
'thingamy|bell and whistle',
'beside oneself|amok',
'amok|beside oneself',
'beside the point|amiss',
'amiss|beside the point',
'beside the question|not on the merits',
'not on the merits|beside the question',
'best regards|with best wishes',
'with best wishes|best regards',
'best wishes|with best wishes',
'with best wishes|best wishes',
'between what|between what',
'between what|between what',
'beyond all doubt|no doubt',
'no doubt|beyond all doubt',
'beyond belief|unbelievable',
'unbelievable|beyond belief',
'beyond hope|hopelessly',
'hopelessly|beyond hope',
'big game|big game',
'big game|big game',
'big shot|a great big noise',
'a great big noise|big shot',
'big time|the leading roles, positions',
'the leading roles, positions|big time',
'bit by bit|a little',
'a little|bit by bit',
'bitter end|the end',
'the end|bitter end',
'black board|whiteboard',
'whiteboard|black board',
'black eye|black eye',
'black eye|black eye',
'black out|seal',
'seal|black out',
'black sheep|black sheep',
'black sheep|black sheep',
'block letter|printed letter',
'printed letter|block letter',
'blow up|explode, humbug',
'explode, humbug|blow up',
'book keeper|Accountant',
'Accountant|book keeper',
'bound back|bounce',
'bounce|bound back',
'bow down|bow',
'bow|bow down',
'bow out|retire',
'retire|bow out',
'bowl out|obfuscate',
'obfuscate|bowl out',
'branch house|Branch',
'Branch|branch house',
'branch off|to enhance',
'to enhance|branch off',
'break down|wrestle',
'wrestle|break down',
'break line|red line',
'red line|break line',
'break off|break off',
'break off|break off',
'break open|break',
'break|break open',
'break up|diverge',
'diverge|break up',
'bring about|cause',
'cause|bring about',
'bring forth|to nominate',
'to nominate|bring forth',
'bring forward|to nominate',
'to nominate|bring forward',
'bring into play|exercise',
'exercise|bring into play',
'bring into step|Synchronize',
'Synchronize|bring into step',
'bring out|to make',
'to make|bring out',
'bring to light|to detect',
'to detect|bring to light',
'bring under|to suppress',
'to suppress|bring under',
'bring up|raise',
'raise|bring up',
'broad hint|a clear hint',
'a clear hint|broad hint',
'broad jump|long jump',
'long jump|broad jump',
'burst into|burst',
'burst|burst into',
'burst out|erupt',
'erupt|burst out',
'but for|if not',
'if not|but for',
'but then|but',
'but|but then',
'by and by|soon',
'soon|by and by',
'by and large|in general',
'in general|by and large',
'by chance|by accident',
'by accident|by chance',
'by end of|by the end of',
'by the end of|by end of',
'by enough|without doubt',
'without doubt|by enough',
'by eye|the eye, approximately',
'the eye, approximately|by eye',
'by far|much',
'much|by far',
'by half|half',
'half|by half',
'by hand|hand',
'hand|by hand',
'by the way|the way',
'the way|by the way',
'by then|at that time',
'at that time|by then',
'cabbage soap|cabbage soup',
'cabbage soup|cabbage soap',
'call back|back, call back',
'back, call back|call back',
'call bell|alarm bell',
'alarm bell|call bell',
'call into action|exercise',
'exercise|call into action',
'call of duty|the duty of service',
'the duty of service|call of duty',
'call off|repeal',
'repeal|call off',
'call on|to visit',
'to visit|call on',
'calm down|calm down',
'calm down|calm down',
'camp out|sleeping in a tent',
'sleeping in a tent|camp out',
'cancel out|to neutralize',
'to neutralize|cancel out',
'card face|Front',
'Front|card face',
'carry away|claim',
'claim|carry away',
'carry forward|to transport',
'to transport|carry forward',
'carry in|put in',
'put in|carry in',
'carry on|to continue',
'to continue|carry on',
'carry out|perform',
'perform|carry out',
'carry over|transfer',
'transfer|carry over',
'carry too far|go too far',
'go too far|carry too far',
'case law|judicial pretsendent',
'judicial pretsendent|case law',
'cast back|push',
'push|cast back',
'cast off|reset',
'reset|cast off',
'cast out|cast',
'cast|cast out',
'catch a chill|prostuzhatsya',
'prostuzhatsya|catch a chill',
'catch a cold|prostuditsya',
'prostuditsya|catch a cold',
'catch fire|fire',
'fire|catch fire',
'catch ones eye|to attract ones attention',
'to attract ones attention|catch ones eye',
'catch out|to detect',
'to detect|catch out',
'catch up (with)|catch up',
'catch up|catch up (with)',
'cause of auction|a cause for action',
'a cause for action|cause of auction',
'chance on|to detect',
'to detect|chance on',
'change for the worst|a change for the worse',
'a change for the worse|change for the worst',
'change hands|change hands',
'change hands|change hands',
'change into|turn',
'turn|change into',
'change over|switch',
'switch|change over',
'channel away|to give',
'to give|channel away',
'character set|a set of characters',
'a set of characters|character set',
'charge back|to receive',
'to receive|charge back',
'chase away|boo',
'boo|chase away',
'check back|recheck',
'recheck|check back',
'check in|register',
'register|check in',
'check out|out',
'out|check out',
'check up|check',
'check|check up',
'check weight|controlling weight',
'controlling weight|check weight',
'cheer up|to encourage',
'to encourage|cheer up',
'chiken out|a coward',
'a coward|chiken out',
'chime in|get a word in edgeways',
'get a word in edgeways|chime in',
'chop down|cut down',
'cut down|chop down',
'chop off|chop off',
'chop off|chop off',
'chop up|chop',
'chop|chop up',
'city hall|City Hall',
'City Hall|city hall',
'clean up|direct order',
'direct order|clean up',
'clear eyed|a visionary',
'a visionary|clear eyed',
'clear up|to ascertain',
'to ascertain|clear up',
'clock wise|clockwise',
'clockwise|clock wise',
'close a deal|bargain',
'bargain|close a deal',
'close attention|attention',
'attention|close attention',
'close check|strict control',
'strict control|close check',
'come about|occur',
'occur|come about',
'come across|to find',
'to find|come across',
'come along|join',
'join|come along',
'come around|to accept',
'to accept|come around',
'come at|reach',
'reach|come at',
'come away|away',
'away|come away',
'come back|to return',
'to return|come back',
'come before|before',
'before|come before',
'come by|get, acquire',
'get, acquire|come by',
'come down|down',
'down|come down',
'come for|call for',
'call for|come for',
'come from|have come from',
'have come from|come from',
'come in|to enter',
'to enter|come in',
'come off|stall',
'stall|come off',
'come out|appear',
'appear|come out',
'come to an end|end',
'end|come to an end',
'come to terms|to agree',
'to agree|come to terms',
'come true|carried out',
'carried out|come true',
'come up|arise',
'arise|come up',
'concerned about|is concerned',
'is concerned|concerned about',
'confer with|together',
'together|confer with',
'contend that|to argue that',
'to argue that|contend that',
'cook up|to invent',
'to invent|cook up',
'cool cheek|cheek',
'cheek|cool cheek',
'cool down|cool',
'cool|cool down',
'count for|have a value',
'have a value|count for',
'count on|to count.',
'to count.|count on',
'count out|delete',
'delete|count out',
'count up|count',
'count|count up',
'cross border|overseas',
'overseas|cross border',
'cross country|cross',
'cross|cross country',
'cross off|expunge',
'expunge|cross off',
'cross road|crossroad',
'crossroad|cross road',
'cry down|ban',
'ban|cry down',
'cry for|claim',
'claim|cry for',
'cry off|to abandon intentions',
'to abandon intentions|cry off',
'cry out|to declare publicly',
'to declare publicly|cry out',
'cry up|praise',
'praise|cry up',
'cut above|much better',
'much better|cut above',
'cut away|cut',
'cut|cut away',
'cut back|cut',
'cut|cut back',
'cut classes|truant lessons',
'truant lessons|cut classes',
'cut corners|to save',
'to save|cut corners',
'cut down|cut',
'cut|cut down',
'cut glass|crystal',
'crystal|cut glass',
'cut off|turn off',
'turn off|cut off',
'cut out|to stop',
'to stop|cut out',
'cut short|cut',
'cut|cut short',
'cut up|cut',
'cut|cut up',
'daily wants|the urgent needs',
'the urgent needs|daily wants',
'dark horse|dark horse',
'dark horse|dark horse',
'dash out|run out',
'run out|dash out',
'day after day|day in and day out',
'day in and day out|day after day',
'day after tomorrow|day after tomorrow',
'day after tomorrow|day after tomorrow',
'day by day|day after day',
'day after day|day by day',
'day in and day out|one day',
'one day|day in and day out',
'day off|a public holiday',
'a public holiday|day off',
'dead against|strongly opposed',
'strongly opposed|dead against',
'dead duck|dohloe case',
'dohloe case|dead duck',
'dead letter|Undelivered Letter',
'Undelivered Letter|dead letter',
'dead lift|a complex case',
'a complex case|dead lift',
'dead line|Prohibited feature',
'Prohibited feature|dead line',
'deal a blow|strike',
'strike|deal a blow',
'deal amiss|err',
'err|deal amiss',
'deal out|donate',
'donate|deal out',
'deal with|deal',
'deal|deal with',
'death house|on death row',
'on death row|death house',
'debt load|the burden of debt',
'the burden of debt|debt load',
'decide against|reject',
'reject|decide against',
'deep space|outer space',
'outer space|deep space',
'desk book|a handbook',
'a handbook|desk book',
'die away|die',
'die|die away',
'dig in|retrench',
'retrench|dig in',
'dig out|dig',
'dig|dig out',
'dig up|trench',
'trench|dig up',
'do a thing|take care',
'take care|do a thing',
'do away|to end',
'to end|do away',
'do not care|still',
'still|do not care',
'do over|remodel',
'remodel|do over',
'do well|to thrive',
'to thrive|do well',
'do with|met',
'met|do with',
'do without|do',
'do|do without',
'down payment|earnest',
'earnest|down payment',
'down pour|Showers',
'Showers|down pour',
'down time|downtime',
'downtime|down time',
'draft only|a draft contract',
'a draft contract|draft only',
'drag and drop|redeployment',
'redeployment|drag and drop',
'draw in|draw',
'draw|draw in',
'draw on a|issue',
'issue|draw on a',
'draw to do|force to make',
'force to make|draw to do',
'dress up|wear',
'wear|dress up',
'drop a hint of doubt|cast a shadow of doubt',
'cast a shadow of doubt|drop a hint of doubt',
'drop across|to punish',
'to punish|drop across',
'duck blind|ambush',
'ambush|duck blind',
'duck soup|nothing',
'nothing|duck soup',
'each and all|all',
'all|each and all',
'each and every|all',
'all|each and every',
'each of which|who',
'who|each of which',
'each other|each other',
'each other|each other',
'early days|the initial period',
'the initial period|early days',
'early in|in the beginning',
'in the beginning|early in',
'early on|earlier',
'earlier|early on',
'easy does it|cautiously',
'cautiously|easy does it',
'eat away|bite',
'bite|eat away',
'eat in|eat at home',
'eat at home|eat in',
'eat into|eat in',
'eat in|eat into',
'eat out|dine outside the home',
'dine outside the home|eat out',
'edge up to|to change slightly to',
'to change slightly to|edge up to',
'egg on|egg',
'egg|egg on',
'egg white|egg white',
'egg white|egg white',
'either up or down|as up and down',
'as up and down|either up or down',
'eke out a living|scratch anyhow',
'scratch anyhow|eke out a living',
'empty heanded|frivolous',
'frivolous|empty heanded',
'end point|off',
'off|end point',
'end to end|a cross-cutting',
'a cross-cutting|end to end',
'end up|finish',
'finish|end up',
'enjoy the right|have the right',
'have the right|enjoy the right',
'enter up|to record',
'to record|enter up',
'enter upon|start',
'start|enter upon',
'errand boy|messenger',
'messenger|errand boy',
'even out|dress',
'dress|even out',
'even so|all the same',
'all the same|even so',
'ever after|since then',
'since then|ever after',
'ever so|well',
'well|ever so',
'every other|every second',
'every second|every other',
'every so often|sometimes',
'sometimes|every so often',
'evil eye|evil eye',
'evil eye|evil eye',
'eye witness|witness',
'witness|eye witness',
'face a dilemma|face a dilemma',
'face a dilemma|face a dilemma',
'face difficulties|to face difficulties',
'to face difficulties|face difficulties',
'face the|to meet with',
'to meet with|face the',
'face to face|face to face',
'face to face|face to face',
'face up to|be ready to',
'be ready to|face up to',
'fact that|that',
'that|fact that',
'fade away|gone, faded out',
'gone, faded out|fade away',
'fade in|to grow',
'to grow|fade in',
'fade out|to weaken',
'to weaken|fade out',
'fall apart|dilapidate',
'dilapidate|fall apart',
'fall back|to reduce',
'to reduce|fall back',
'fall down|to fall',
'to fall|fall down',
'fall into|enter',
'enter|fall into',
'fall off|to weaken',
'to weaken|fall off',
'fall out|fall',
'fall|fall out',
'fall over|tip',
'tip|fall over',
'fall within|lie within the',
'lie within the|fall within',
'far and away|far',
'far|far and away',
'far and by|in general',
'in general|far and by',
'far and near|everywhere',
'everywhere|far and near',
'far away|far',
'far|far away',
'far cry|long distance',
'long distance|far cry',
'far cry from|far from',
'far from|far cry from',
'far less|much less',
'much less|far less',
'far more|much more',
'much more|far more',
'far off|far',
'far|far off',
'farm hand|Assistant',
'Assistant|farm hand',
'fear of the unknown|fear of the unknown',
'fear of the unknown|fear of the unknown',
'feel bad|to be guilty',
'to be guilty|feel bad',
'feel up to|be able to',
'be able to|feel up to',
'few at a time|briefly',
'briefly|few at a time',
'fifty-fifty|half',
'half|fifty-fifty',
'figure out|to understand',
'to understand|figure out',
'find no sense|no sense',
'no sense|find no sense',
'find out|to detect',
'to detect|find out',
'fire up|start',
'start|fire up',
'first go|the first case',
'the first case|first go',
'first of all|the first case',
'the first case|first of all',
'fish for|ask for',
'ask for|fish for',
'fish out of|fish from',
'fish from|fish out of',
'fix out|to ensure',
'to ensure|fix out',
'fix up|repair, fix',
'repair, fix|fix up',
'flag down|holler',
'holler|flag down',
'fly away|fly away',
'fly away|fly away',
'fly off|depart',
'depart|fly off',
'fly open|break',
'break|fly open',
'fog up|steam',
'steam|fog up',
'for about|approximately',
'approximately|for about',
'for all that|despite all this',
'despite all this|for all that',
'for all we know|as far as we know',
'as far as we know|for all we know',
'for around|about',
'about|for around',
'for as long as|as much as',
'as much as|for as long as',
'for ever|forever',
'forever|for ever',
'for every two|for each of the two',
'for each of the two|for every two',
'for free|free of charge',
'free of charge|for free',
'for sure|no doubt',
'no doubt|for sure',
'for the best|the best',
'the best|for the best',
'for the rest|the rest',
'the rest|for the rest',
'for up to|until',
'until|for up to',
'for want of|for lack of',
'for lack of|for want of',
'free up|release',
'release|free up',
'from here|here',
'here|from here',
'from there|from there',
'from there|from there',
'from under|from custody',
'from custody|from under',
'gain over|to convince',
'to convince|gain over',
'game of|game',
'game|game of',
'gate out|excluded',
'excluded|gate out',
'gear box|gearbox',
'gearbox|gear box',
'get a line|to obtain information',
'to obtain information|get a line',
'get about|extended',
'extended|get about',
'get ahead of|surpass',
'surpass|get ahead of',
'get along with|get along',
'get along|get along with',
'get around|bypass',
'bypass|get around',
'get at|to ascertain',
'to ascertain|get at',
'get down to|take',
'take|get down to',
'get hurt|bruise',
'bruise|get hurt',
'get in on|interest',
'interest|get in on',
'get in touch|contact',
'contact|get in touch',
'get into|get into',
'get into|get into',
'get off|go',
'go|get off',
'get out|out',
'out|get out',
'get set to|meet',
'meet|get set to',
'get the foot|ahead of',
'ahead of|get the foot',
'get the hand|master',
'master|get the hand',
'get to know|to understand',
'to understand|get to know',
'get together|meet',
'meet|get together',
'get up|get up',
'get up|get up',
'get well|to recover',
'to recover|get well',
'give a clue|put on the trail',
'put on the trail|give a clue',
'give a lift|haul',
'haul|give a lift',
'give account|to take into account',
'to take into account|give account',
'give an edge|to strengthen',
'to strengthen|give an edge',
'give an eye to|to pay attention to',
'to pay attention to|give an eye to',
'give away|to give',
'to give|give away',
'give head|not to interfere',
'not to interfere|give head',
'give off|to provide',
'to provide|give off',
'give rise|to create',
'to create|give rise',
'give up|to leave, to refuse',
'to leave, to refuse|give up',
'glee club|a choral circle',
'a choral circle|glee club',
'global reach|the world achievement',
'the world achievement|global reach',
'go abreast of|not lag behind',
'not lag behind|go abreast of',
'go ahead|continue',
'continue|go ahead',
'go all out|the maximum speed',
'the maximum speed|go all out',
'go away|to leave, leave',
'to leave, leave|go away',
'go back|to return',
'to return|go back',
'go bad|a leakage',
'a leakage|go bad',
'go bail|bail',
'bail|go bail',
'go between|take place between',
'take place between|go between',
'go beyond|beyond',
'beyond|go beyond',
'go by|pass by',
'pass by|go by',
'go down to|drops',
'drops|go down to',
'go in|to enter the',
'to enter the|go in',
'go into|join',
'join|go into',
'go mad|mad',
'mad|go mad',
'go on|to continue',
'to continue|go on',
'go out|go',
'go|go out',
'go over to|to move to',
'to move to|go over to',
'go to bed|go to bed',
'go to bed|go to bed',
'go to zero|vanish',
'vanish|go to zero',
'go through|go through',
'go through|go through',
'go up to|grow up to',
'grow up to|go up to',
'go-no-go|good, not good',
'good, not good|go-no-go',
'gold leaf|gold leaf',
'gold leaf|gold leaf',
'good deal|a lot',
'a lot|good deal',
'good few|a good half',
'a good half|good few',
'good while|quite a long time',
'quite a long time|good while',
'grasp the idea|to think about',
'to think about|grasp the idea',
'great care|account',
'account|great care',
'great while|a long time',
'a long time|great while',
'grin and bear it|to make good the mine when a bad game',
'to make good the mine when a bad game|grin and bear it',
'grind for a bit|poschelkivat',
'poschelkivat|grind for a bit',
'ground coffee|coffee beans',
'coffee beans|ground coffee',
'ground cover|vegetation',
'vegetation|ground cover',
'ground floor|first floor',
'first floor|ground floor',
'grow dark|dark',
'dark|grow dark',
'grow up|grow up',
'grow up|grow up',
'guard against|to avoid',
'to avoid|guard against',
'hack on|to work on',
'to work on|hack on',
'hack together|hammer together',
'hammer together|hack together',
'half as much|half',
'half|half as much',
'half brother|half-brother',
'half-brother|half brother',
'half sister|stepsister',
'stepsister|half sister',
'ham radio|short-wave radio',
'short-wave radio|ham radio',
'hang around|stick, hang idle',
'stick, hang idle|hang around',
'hand out|to issue',
'to issue|hand out',
'hand over|pass',
'pass|hand over',
'hand-to-hand|hand-to-hand',
'hand-to-hand|hand-to-hand',
'hang up|turn off',
'turn off|hang up',
'happy birthday|happy birthday',
'happy birthday|happy birthday',
'hardly at all|almost anything',
'almost anything|hardly at all',
'hardly ever|hardly ever',
'hardly ever|hardly ever',
'have a loss|suffer damage',
'suffer damage|have a loss',
'have but to|should only',
'should only|have but to',
'have much to do|have much in common',
'have much in common|have much to do',
'head cold|a runny nose',
'a runny nose|head cold',
'head wind|cross-wind',
'cross-wind|head wind',
'heaven and earth|all funds',
'all funds|heaven and earth',
'heavy duty|work in heavy duty',
'work in heavy duty|heavy duty',
'heavy repair|overhaul',
'overhaul|heavy repair',
'help with|try',
'try|help with',
'high school|high school',
'high school|high school',
'high sign|symbol',
'symbol|high sign',
'hit back|hit back',
'hit back|hit back',
'hit by|suffer greatly from',
'suffer greatly from|hit by',
'hit or miss|at random',
'at random|hit or miss',
'hit the road|go on a journey',
'go on a journey|hit the road',
'hold all the cards|have an edge',
'have an edge|hold all the cards',
'hold back|to hide',
'to hide|hold back',
'hold down|hold',
'hold|hold down',
'hold in|hold',
'hold|hold in',
'hold in check|to deter',
'to deter|hold in check',
'hold it|stop!, wait!; Stand!',
'stop!, wait!; Stand!|hold it',
'hold over|postponed',
'postponed|hold over',
'hold that|to believe that',
'to believe that|hold that',
'hold up|to attack',
'to attack|hold up',
'hot dog|sausage',
'sausage|hot dog',
'how are you|how are you',
'how are you|how are you',
'how come|why',
'why|how come',
'how do you do|how are you',
'how are you|how do you do',
'how long|how many',
'how many|how long',
'how many|how many',
'how many|how many',
'how much|but',
'but|how much',
'hue and cry|noise',
'noise|hue and cry',
'hurry over|to throw together',
'to throw together|hurry over',
'hurry up|hurry',
'hurry|hurry up',
'I am fine|I have everything perfectly',
'I have everything perfectly|I am fine',
'ice cream|ice cream',
'ice cream|ice cream',
'idle attempt|a futile attempt',
'a futile attempt|idle attempt',
'if and only if|then and only then',
'then and only then|if and only if',
'if at all|if at all',
'if at all|if at all',
'ill at easy|embarrassing',
'embarrassing|ill at easy',
'ill turn|poor service',
'poor service|ill turn',
'improve away|when you try to degrade improve',
'when you try to degrade improve|improve away',
'in a broad manner|in general',
'in general|in a broad manner',
'in a day or two|the other day',
'the other day|in a day or two',
'in a draw|a draw',
'a draw|in a draw',
'in a little while|soon',
'soon|in a little while',
'in a manner|to some extent',
'to some extent|in a manner',
'in a sense|in a sense',
'in a sense|in a sense',
'in a way|in some respects',
'in some respects|in a way',
'in about|about a',
'about a|in about',
'in as much as|as',
'as|in as much as',
'in behalf of|for',
'for|in behalf of',
'in brief|in a nutshell',
'in a nutshell|in brief',
'in error|mistakenly',
'mistakenly|in error',
'in fact|in fact,',
'in fact,|in fact',
'in front of|before',
'before|in front of',
'in itself|by its very nature',
'by its very nature|in itself',
'in nature|by origin',
'by origin|in nature',
'in no time|immediately',
'immediately|in no time',
'in no way|any way',
'any way|in no way',
'in place of|instead of',
'instead of|in place of',
'in short|short',
'short|in short',
'in so far as|because',
'because|in so far as',
'in such a way|in a way',
'in a way|in such a way',
'in the face|before',
'before|in the face',
'in this way|this way',
'this way|in this way',
'in vain|in vain',
'in vain|in vain',
'in what way|how',
'how|in what way',
'initial lot|pilot batch',
'pilot batch|initial lot',
'into the name of|in the name of',
'in the name of|into the name of',
'is, that|that',
'that|is, that',
'it is best to|the best',
'the best|it is best to',
'it pays|it makes sense',
'it makes sense|it pays',
'jazz up|animate',
'animate|jazz up',
'job title|post',
'post|job title',
'jump at conclusions|to make hasty conclusions',
'to make hasty conclusions|jump at conclusions',
'jump at the bait|fall for',
'fall for|jump at the bait',
'jump down|jump',
'jump|jump down',
'jump on the bandwagon|rush pell-mell',
'rush pell-mell|jump on the bandwagon',
'jump the track|provided the wrong way',
'provided the wrong way|jump the track',
'just as|just as',
'just as|just as',
'just so|quite rightly',
'quite rightly|just so',
'just the same|exactly the same',
'exactly the same|just the same',
'just when|the second time',
'the second time|just when',
'keen on|rapt',
'rapt|keen on',
'keep a check on|monitor',
'monitor|keep a check on',
'keep a diary|to keep a diary',
'to keep a diary|keep a diary',
'keep abreast of|to keep pace with',
'to keep pace with|keep abreast of',
'keep alert|be ready',
'be ready|keep alert',
'keep cool|not to worry',
'not to worry|keep cool',
'keep down|delay',
'delay|keep down',
'keep in check|to deter',
'to deter|keep in check',
'keep in mind|bear in mind',
'bear in mind|keep in mind',
'keep in sight|do not lose sight of',
'do not lose sight of|keep in sight',
'keep in touch|to liaise',
'to liaise|keep in touch',
'keep in viev|bear in mind',
'bear in mind|keep in viev',
'keep on|to continue',
'to continue|keep on',
'keep open|to remain accessible',
'to remain accessible|keep open',
'keep out of|take care of',
'take care of|keep out of',
'keep pace|to keep pace',
'to keep pace|keep pace',
'keep track|to follow',
'to follow|keep track',
'keep up|to support',
'to support|keep up',
'key off|turn off',
'turn off|key off',
'key on|include',
'include|key on',
'kick off|start',
'start|kick off',
'knock down|to destroy, degrade',
'to destroy, degrade|knock down',
'knock off|to destroy, reset',
'to destroy, reset|knock off',
'knock out|emboss',
'emboss|knock out',
'lap dog|lap-dog',
'lap-dog|lap dog',
'large order|a difficult case',
'a difficult case|large order',
'last but not least|last but not least',
'last but not least|last but not least',
'last but one|the last',
'the last|last but one',
'lay aside|postponed',
'postponed|lay aside',
'lay down|to formulate',
'to formulate|lay down',
'lay eyes|to see',
'to see|lay eyes',
'lay off|dismiss',
'dismiss|lay off',
'lead astray|confuse the devil',
'confuse the devil|lead astray',
'lead away|sweep',
'sweep|lead away',
'lead into error|misleading',
'misleading|lead into error',
'lead off|open',
'open|lead off',
'lead time|Cycle',
'Cycle|lead time',
'lean and clean|a cost',
'a cost|lean and clean',
'leave aside|ignored',
'ignored|leave aside',
'leave behind|ahead of',
'ahead of|leave behind',
'leave off|interrupt',
'interrupt|leave off',
'leave out|skip',
'skip|leave out',
'leave over|postponed',
'postponed|leave over',
'lend itself to|suitable for',
'suitable for|lend itself to',
'let down|down',
'down|let down',
'let go|let go',
'let go|let go',
'let in on|to devote to',
'to devote to|let in on',
'let out|to produce, release',
'to produce, release|let out',
'like the book|know, like a book',
'know, like a book|like the book',
'lit out for|go to',
'go to|lit out for',
'lock away|block',
'block|lock away',
'lock up|block',
'block|lock up',
'long for|wait eagerly',
'wait eagerly|long for',
'look about|search',
'search|look about',
'look after|to look for',
'to look for|look after',
'look as|just like',
'just like|look as',
'look for|search',
'search|look for',
'look for help|to rely on aid',
'to rely on aid|look for help',
'look forvard|hopefully',
'hopefully|look forvard',
'look like|be like',
'be like|look like',
'look on|to consider',
'to consider|look on',
'look out|look',
'look|look out',
'look over|see',
'see|look over',
'look upon|to consider',
'to consider|look upon',
'lose a round|play',
'play|lose a round',
'lost in|tangle in',
'tangle in|lost in',
'made up with|compensate',
'compensate|made up with',
'major discount|a discount',
'a discount|major discount',
'make a bet|to bet',
'to bet|make a bet',
'make a date|to appoint a date',
'to appoint a date|make a date',
'make a deal|bargain',
'bargain|make a deal',
'make a vow|to give an oath',
'to give an oath|make a vow',
'make clear|to explain',
'to explain|make clear',
'make free|open access',
'open access|make free',
'make fun|to mock',
'to mock|make fun',
'make good|to reimburse',
'to reimburse|make good',
'make it clear|to understand',
'to understand|make it clear',
'make love to|to care for',
'to care for|make love to',
'make out|to understand a',
'to understand a|make out',
'make plain|to explain',
'to explain|make plain',
'make room|release',
'release|make room',
'make up|create',
'create|make up',
'make-up|Cosmetics',
'Cosmetics|make-up',
'man on duty|duty',
'duty|man on duty',
'many a time|often',
'often|many a time',
'mark down|lower',
'lower|mark down',
'mark off|mark',
'mark|mark off',
'mark up|raise',
'raise|mark up',
'mean life|the average lifespan',
'the average lifespan|mean life',
'mess up|mix',
'mix|mess up',
'miss a best|confuse rhythm',
'confuse rhythm|miss a best',
'mix up|confusion',
'confusion|mix up',
'money box|moneybox',
'moneybox|money box',
'monkey business|freak',
'freak|monkey business',
'more accurate|more specifically',
'more specifically|more accurate',
'more like|rather',
'rather|more like',
'more so|so much so that',
'so much so that|more so',
'morning coat|cutaway',
'cutaway|morning coat',
'most of all|the most',
'the most|most of all',
'most often|more often than not',
'more often than not|most often',
'move down|move',
'move|move down',
'move on|pass',
'pass|move on',
'move over to|to move in',
'to move in|move over to',
'move up to|please contact',
'please contact|move up to',
'much of|most of',
'most of|much of',
'much the same|almost the same',
'almost the same|much the same',
'nagging fear|fear of goofy',
'fear of goofy|nagging fear',
'nail down|to conclude',
'to conclude|nail down',
'naked eye|the naked eye',
'the naked eye|naked eye',
'narrow down|to reduce',
'to reduce|narrow down',
'navy blue|dark blue',
'dark blue|navy blue',
'near by|next to',
'next to|near by',
'needle eye|eye of a needle',
'eye of a needle|needle eye',
'neither for or against|neither for nor against',
'neither for nor against|neither for or against',
'next door|close',
'close|next door',
'nip and tuck|neck and neck',
'neck and neck|nip and tuck',
'no doubt|no doubt',
'no doubt|no doubt',
'no way|for nothing',
'for nothing|no way',
'none at all|absolutely nothing',
'absolutely nothing|none at all',
'not a bit|none',
'none|not a bit',
'not after|toko after',
'toko after|not after',
'not at all|not at all',
'not at all|not at all',
'now and again|from time to time',
'from time to time|now and again',
'oath of office|oath',
'oath|oath of office',
'odd and even|clear and Nechet',
'clear and Nechet|odd and even',
'odd job|jobbing',
'jobbing|odd job',
'of course|of course',
'of course|of course',
'of late|the last time',
'the last time|of late',
'of note|known',
'known|of note',
'of the same|the same',
'the same|of the same',
'off day|output',
'output|off day',
'off hand|without preparation',
'without preparation|off hand',
'old hand|shredded file',
'shredded file|old hand',
'on account of|because of',
'because of|on account of',
'on and again|from time to time',
'from time to time|on and again',
'on foot|walking',
'walking|on foot',
'on how to|how',
'how|on how to',
'on the alert|alert',
'alert|on the alert',
'on the eve|the day before',
'the day before|on the eve',
'on the part of|by',
'by|on the part of',
'once more|again',
'again|once more',
'one another|each other',
'each other|one another',
'one at a time|alternately',
'alternately|one at a time',
'one by one|one by one',
'one by one|one by one',
'one more|another',
'another|one more',
'other day|the other day',
'the other day|other day',
'other than|other than',
'other than|other than',
'other way around|on the contrary',
'on the contrary|other way around',
'out and out|desperate',
'desperate|out and out',
'out of danger|out of danger',
'out of danger|out of danger',
'out of date|outdated',
'outdated|out of date',
'out of the way|finally',
'finally|out of the way',
'over and above|the same',
'the same|over and above',
'over and over|many times',
'many times|over and over',
'over the left|quite the contrary',
'quite the contrary|over the left',
'pack of lies|pack of lies',
'pack of lies|pack of lies',
'pair off|separated in pairs',
'separated in pairs|pair off',
'palm off|vsuchivat',
'vsuchivat|palm off',
'pan out|burn',
'burn|pan out',
'part time|partly',
'partly|part time',
'pass ahead|ahead of',
'ahead of|pass ahead',
'pass away|go',
'go|pass away',
'pass off|disappear',
'disappear|pass off',
'patch up|compose',
'compose|patch up',
'pen name|a pseudonym',
'a pseudonym|pen name',
'pen pal|a friend of correspondence',
'a friend of correspondence|pen pal',
'pick out|to choose',
'to choose|pick out',
'pick up|buy, haul, to take',
'buy, haul, to take|pick up',
'pipe down|deduct tone',
'deduct tone|pipe down',
'pipe up|talk',
'talk|pipe up',
'place a premium|to encourage',
'to encourage|place a premium',
'place name|the geographical name',
'the geographical name|place name',
'play safe|to avoid the risk of',
'to avoid the risk of|play safe',
'play the part|to play a role',
'to play a role|play the part',
'pop in|look',
'look|pop in',
'pop out|to show',
'to show|pop out',
'pot shot|shot at point-blank',
'shot at point-blank|pot shot',
'praise be to god|thank goodness',
'thank goodness|praise be to god',
'present-day|today',
'today|present-day',
'press for more|insist on more',
'insist on more|press for more',
'pretty up|gloss',
'gloss|pretty up',
'prove out|confirm',
'confirm|prove out',
'pry into|poke his nose in',
'poke his nose in|pry into',
'pull down|down',
'down|pull down',
'pull out|pull out',
'pull out|pull out',
'pull up|get to stay',
'get to stay|pull up',
'put around|spread',
'spread|put around',
'put away|clean',
'clean|put away',
'put down|burn',
'burn|put down',
'put forward|to nominate',
'to nominate|put forward',
'put in|paste',
'paste|put in',
'put into use|to begin to apply',
'to begin to apply|put into use',
'put off|postponed',
'postponed|put off',
'put out|to produce',
'to produce|put out',
'put over|postponed',
'postponed|put over',
'rabbits foot|a talisman for luck',
'a talisman for luck|rabbits foot',
'rain and shine|in all weathers',
'in all weathers|rain and shine',
'rake up|dig',
'dig|rake up',
'rally above|more than',
'more than|rally above',
'range over|cover',
'cover|range over',
'real estate|real estate',
'real estate|real estate',
'reason a fear away|razveivat fears dovadami',
'razveivat fears dovadami|reason a fear away',
'red tape|tape',
'tape|red tape',
'reel off|issue',
'issue|reel off',
'relay race|relay',
'relay|relay race',
'rest upon|lie at the',
'lie at the|rest upon',
'return trip|way back',
'way back|return trip',
'ride away|pull off',
'pull off|ride away',
'right away|immediately',
'immediately|right away',
'ring off|switch off',
'switch off|ring off',
'ring out|handed',
'handed|ring out',
'ring up|call',
'call|ring up',
'roll call|roll',
'roll|roll call',
'roll down|roll',
'roll|roll down',
'roll up|roll',
'roll|roll up',
'root for|root for',
'root for|root for',
'root out|to eliminate',
'to eliminate|root out',
'rough and ready|hasty',
'hasty|rough and ready',
'round off|round',
'round|round off',
'rule out|excluded',
'excluded|rule out',
'run across|face',
'face|run across',
'run away|run away',
'run away|run away',
'run by|lead',
'lead|run by',
'run down|stop',
'stop|run down',
'run into|meet',
'meet|run into',
'run low|dry',
'dry|run low',
'run off|cut and run, run away',
'cut and run, run away|run off',
'run out|end',
'end|run out',
'run over|view',
'view|run over',
'run up to|go up',
'go up|run up to',
'safe and sound|unhurt',
'unhurt|safe and sound',
'same that|identical',
'identical|same that',
'save for|except',
'except|save for',
'second hand|Used',
'Used|second hand',
'see about|to care for',
'to care for|see about',
'see here|listen',
'listen|see here',
'see last of|to finish',
'to finish|see last of',
'sell off|sell out',
'sell out|sell off',
'sell out|sell out',
'sell out|sell out',
'send forth|to produce',
'to produce|send forth',
'serve upon|to file',
'to file|serve upon',
'set apart|postponed',
'postponed|set apart',
'set aside|reject',
'reject|set aside',
'set down|put, put',
'put, put|set down',
'set forth|to present',
'to present|set forth',
'set forward|to nominate',
'to nominate|set forward',
'set free|release',
'release|set free',
'set up|set',
'set|set up',
'shake down|fling off',
'fling off|shake down',
'shake off|otryahivat',
'otryahivat|shake off',
'shake up|fling off',
'fling off|shake up',
'shop window|showcase',
'showcase|shop window',
'show off|cut a wide swath',
'cut a wide swath|show off',
'show up|to appear',
'to appear|show up',
'shut down|turn off',
'turn off|shut down',
'shut up|stop',
'stop|shut up',
'sit back|otkidyvatsya',
'otkidyvatsya|sit back',
'sit down|sit down',
'sit down|sit down',
'sit out|to sit until the end',
'to sit until the end|sit out',
'sit through|prosizhivat',
'prosizhivat|sit through',
'slim down|lose weight',
'lose weight|slim down',
'slip angle|the angle of the lateral review',
'the angle of the lateral review|slip angle',
'smart ass|wiseacre',
'wiseacre|smart ass',
'snap back|recover',
'recover|snap back',
'snow under|swamp',
'swamp|snow under',
'so as|in order to',
'in order to|so as',
'so far|so far',
'so far|so far',
'so far as|because',
'because|so far as',
'so on|so on',
'so on|so on',
'so so|so-so',
'so-so|so so',
'so what|so what',
'so what|so what',
'some few|a good half',
'a good half|some few',
'speak out|speak clearly',
'speak clearly|speak out',
'speak up|to speak loudly',
'to speak loudly|speak up',
'split up|beat',
'beat|split up',
'stand back|to depart',
'to depart|stand back',
'stand by|shun',
'shun|stand by',
'stand for|represent',
'represent|stand for',
'stand out|stand out',
'stand out|stand out',
'stand over|stand on the soul',
'stand on the soul|stand over',
'stand up|get up',
'get up|stand up',
'stay away|shun',
'shun|stay away',
'stay out|truant',
'truant|stay out',
'stay up|not to go',
'not to go|stay up',
'step aside|give way',
'give way|step aside',
'step back|to depart',
'to depart|step back',
'step by step|gradually',
'gradually|step by step',
'step down|go',
'go|step down',
'step over|transgress',
'transgress|step over',
'step up|raise',
'raise|step up',
'stick by|remain faithful',
'remain faithful|stick by',
'stick out|stick',
'stick|stick out',
'stick up|stick',
'stick|stick up',
'study for|to prepare for',
'to prepare for|study for',
'such as|for example',
'for example|such as',
'such that|so',
'so|such that',
'swear in|swear',
'swear|swear in',
'switch off|turn off',
'turn off|switch off',
'switch on|to include',
'to include|switch on',
'take a look at|look at',
'look at|take a look at',
'take a task|taking into circulation',
'taking into circulation|take a task',
'take away|take away',
'take away|take away',
'take back|to return',
'to return|take back',
'take care of|take care of',
'take care of|take care of',
'take down|to dismantle',
'to dismantle|take down',
'take off|to withdraw',
'to withdraw|take off',
'take out|decorate',
'decorate|take out',
'take the time|to find the time',
'to find the time|take the time',
'take up|take',
'take|take up',
'talk turkey|to speak in plain English',
'to speak in plain English|talk turkey',
'tank car|tank',
'tank|tank car',
'tear away|break away',
'break away|tear away',
'tear down|pluck',
'pluck|tear down',
'tear off|cut short',
'cut short|tear off',
'tell apart|to distinguish',
'to distinguish|tell apart',
'tell off|haul',
'haul|tell off',
'thank you very much|thank you very much',
'thank you very much|thank you very much',
'that is why|that is why',
'that is why|that is why',
'then and there|then',
'then|then and there',
'think of as|take',
'take|think of as',
'throw aside|cast',
'cast|throw aside',
'throw away|throw',
'throw|throw away',
'throw off|reset',
'reset|throw off',
'throw open|break',
'break|throw open',
'throw out|throw',
'throw|throw out',
'tips and tricks|trick',
'trick|tips and tricks',
'trial and error|trial and error',
'trial and error|trial and error',
'try back|first start',
'first start|try back',
'tru out|test',
'test|tru out',
'turn around|turn',
'turn|turn around',
'turn aside|deviate',
'deviate|turn aside',
'turn away|away',
'away|turn away',
'turn down|staying',
'staying|turn down',
'turn off|turn off',
'turn off|turn off',
'turn round|rotated',
'rotated|turn round',
'turn up|to strengthen',
'to strengthen|turn up',
'gly duckling|ugly duckling',
'ugly duckling|gly duckling',
'until after|even after the',
'even after the|until after',
'until then|so far',
'so far|until then',
'up against it|hard',
'hard|up against it',
'up and about|on foot',
'on foot|up and about',
'use up|zashodovat',
'zashodovat|use up',
'vacant lot|vacant land',
'vacant land|vacant lot',
'very basic|a significant',
'a significant|very basic',
'wake up|wake up',
'wake up|wake up',
'walk around|walk, to wander around',
'walk, to wander around|walk around',
'walk away|away',
'away|walk away',
'walk back|back, go back, back',
'back, go back, back|walk back',
'walk down|walk, walk, go down',
'walk, walk, go down|walk down',
'walk in|enter',
'enter|walk in',
'walk off|go',
'go|walk off',
'walk out|go',
'go|walk out',
'walk over|to come, treat',
'to come, treat|walk over',
'walk up|suit, approached',
'suit, approached|walk up',
'want ad|ad',
'ad|want ad',
'war cry|battle-cry',
'battle-cry|war cry',
'watch over|to guard',
'to guard|watch over',
'way out|way out',
'way out|way out',
'way up|up',
'up|way up',
'wear and tear|wear',
'wear|wear and tear',
'wear out|wear',
'wear|wear out',
'well above|much higher',
'much higher|well above',
'well ahead off|far ahead',
'far ahead|well ahead off',
'well over|much more',
'much more|well over',
'what about|how about',
'how about|what about',
'witch doctor|witch',
'witch|witch doctor',
'work away|to continue to work',
'to continue to work|work away',
'work out|to develop',
'to develop|work out',
'wtite down|to record',
'to record|wtite down',
'write off|write off',
'write off|write off',
'write out|write',
'write|write out',
'yard sale|Sale',
'Sale|yard sale',
'year term|year period',
'year period|year term',
'yeild the right of way|give way',
'give way|yeild the right of way',
'yes-no|an alternative',
'an alternative|yes-no',
'young and old alike|from low to high',
'from low to high|young and old alike'
);
				for ($i=0;$i<count($f);$i++)
				{
				$a = explode("|",$f[$i]);
				$b = explode(",",$a[1]);
				mt_srand((double)microtime()*1000000);
				$n = mt_rand(0,(count($b)-1));

				$b[$n] = trim($b[$n]);
                $a[0] = trim($a[0]);

//$b[0] = '##11'.$b[0].'##22';
$b[0] = '<font color="#1059C4">'.$b[0].'</font>';

				$cnt = str_replace(" ".$a[0]." "," ".$b[0]." ",$cnt);
				$cnt = str_replace(" ".$a[0].","," ".$b[0].",",$cnt);
				$cnt = str_replace(" ".$a[0]."."," ".$b[0].".",$cnt);
				$cnt = str_replace(" ".$a[0].";"," ".$b[0].";",$cnt);
				$cnt = str_replace(" ".$a[0].":"," ".$b[0].":",$cnt);
				$cnt = str_replace("(".$a[0]." ","(".$b[0]." ",$cnt);
				$cnt = str_replace("(".$a[0].",","(".$b[0].",",$cnt);
				$cnt = str_replace(" ".$a[0].")"," ".$b[0].")",$cnt);
				}
				Return $cnt;
			}




?>

