
<?php

function slang($cnt)
			{
$f = array(
'a lot of bad|bad shit',
'acid head|addict',
'act up|to do something',
'action man|hero',
'adapt|cozy up,try to please',
'addict|acid head',
'aghast|gaga',
'airhead|stupid,goofy person',
'all lies|pack of lies',
'all wet|incorrect,wrong',
'also|just as soon',
'americanism|gimme',
'are you doing|whats up',
'arguing|betcha,in dispute',
'arrange scandal|raise hell',
'as well|just as soon',
'ase|bro,best friend',
'asshole|bad people',
'babble|hot air',
'baby|crumb',
'back off|talk quieter,speak slowly',
'back out|does not contain a promise',
'back up|go back,return',
'bad egg|sick sheep',
'bad people|asshole',
'bad shit|a lot of bad',
'bad|rotten',
'ball of fire|hyperactivity',
'balls|eggs',
'bamboo|dude',
'bananas|crazy',
'bandit|goon',
'bang-up|pregnant',
'bang|having sex',
'barely|in a pigs eye',
'bash|big party',
'bastard|bastard,illegitimate',
'bastard|sleaseball',
'bats|crazy',
'be doomed|luck out',
'beam|dude',
'beat|whale away',
'beautiful girl|knockout',
'beautiful woman|knockout',
'beautiful|dreamboat,handsome',
'beautiful|hunk',
'berk|jerk',
'best friend|ase,bro',
'betcha|arguing,in dispute',
'big boss|big daddy,important knob',
'big cheese|boss',
'big daddy|important knob,big boss',
'big party|bash',
'bigmouth|yap,bitch',
'binge|booz',
'bingo|ready',
'bitch|bigmouth,|yap',
'black|coco,color',
'bloody|damned',
'blow-job|blow',
'blow|blow-job',
'blue|faggy',
'blunder|mop',
'bonehead|goofy,wooden',
'boner|erection',
'boobs|breasts,breast',
'booz|binge',
'bored to the limit|piss off',
'boss|boss',
'boss|top banana',
'brain strain|rack ones brain',
'brave|gutsy',
'breasts|boobs,breast',
'breasts|tits',
'breast|boobs,breasts',
'bribe|kick back',
'bro|ase,best friend',
'bro|man',
'bro|pal',
'buddy|fella',
'buffer|dude',
'bullshit|perfuse',
'bully|piss off',
'bureaucratic red tape|red tape',
'bureaucrats|red tape',
'bush|grass,marijuana',
'by golly|s god',
'call girl|prostitute',
'carry away|institute,worry,trail',
'carry|luck out',
'casanova|tough cat',
'case|duck soup,times plyunu',
'cat|sex',
'chao',
'chatter|yak',
'chick|girl',
'chief|top banana',
'chips|munchies',
'christmas|xmas',
'clear|hot red',
'cock|penis',
'coco|black,color',
'color|coco,black',
'come off it|good shoot the breeze,stop lying',
'competent|earn ones wings',
'cone|top banana',
'confusing|knotty',
'contrive not converge|it doest wash',
'cool|hot red',
'cop|police',
'cowardly|yellow',
'coward|quitter',
'cozy up|adapt,try to please',
'crack a joke|soak,unpin',
'crap|garbage,nonsense',
'crazy man|wacko',
'crazy|bananas',
'crazy|bats',
'crazy|nut',
'creative people|',
'credit card|plastic',
'creep|psycho',
'cross|dude',
'crumb|baby',
'crybaby|sissy',
'cups|tipsy',
'curious|nosy',
'cutthroat|goon',
'dammit|doggoned',
'damned|bloody',
'deadbeat|halyavschik',
'deception|scam',
'defeatist|quitter',
'defeat|fuck up',
'delicious|kicky',
'delight|gee',
'destroyed|goon',
'difficult|knotty',
'dig|like,love',
'dig|sex',
'dinosaur|dino',
'dino|dinosaur',
'dirty work|monkey business',
'distort|twist around',
'do not go|it is no go',
'does not contain a promise|back out',
'doggoned|dammit',
'dollar quarter|two bits',
'doubtful|iffy',
'dreamboat|handsome,beautiful',
'drop a line|drop a line,write a few words',
'dropped drink|on the dry',
'duck soup|times plyunut,case',
'dude|goat,small,man,buffer,bamboo,goon,cross,beam',
'dumb bunny|scapegoat,rag',
'dump the responsibility|pass the back',
'earn ones wings|competent,safe',
'ease up|slow',
'easy|no sweat',
'eat avay|rot',
'eat his words|take ones words',
'eccentric|gaga',
'eccentri|cnut',
'edge out|victory,slight advantage',
'egghead|highbrow',
'eggs|balls',
'elude|ubegat,hide',
'end|wrap',
'engage|entice',
'entice|engage',
'erection|boner',
'excited|uptigh',
'faeces|poo',
'faggy|blue',
'fail|fall flat',
'fail|lay an egg',
'fail|let down',
'fake|footle',
'fall flat|fail',
'fancy|fantastic',
'fantastic|fancy',
'fashion|kicky',
'fella|buddy,period',
'finger wave|obscene gesture,middle finger',
'finish|wrap',
'food|grub',
'fool|knut',
'fool|nut',
'fool|zany',
'fool|zod',
'footle|fake',
'footle|horse around',
'footle|string along',
'fraud|scam',
'freak|queer fish',
'fuck up|defeat',
'fuck you|go to',
'fucker|man',
'fucking|irritation',
'full of energy|gutsy',
'fun|zest',
'fusty|old hat',
'g.i.|private',
'gaga|aghast,eccentric,greetings',
'gang|mob',
'garbage|crap,nonsense',
'garbage|lemon',
'gee|delight,surprise',
'get|piss off',
'gimme|americanism',
'girl|chick',
'give to the paw|kick back',
'go ape|go crazy',
'go back|back up,return',
'go bananas|slip ones trolley',
'go crazy|go ape',
'go to|fuck you',
'goat|dude',
'good shoot the breeze|come off it,stop lying',
'good|zero cool',
'goof up|take a blunder',
'goofy person|airhead,stupid',
'goofy|bonehead,wooden',
'goofy|stupid',
'goon|bandit,destroyed,cutthroat',
'goon|dude',
'grass|bush,marijuana',
'greetings|gaga',
'grind|long work,hard work',
'grub|meals,food',
'grub|slob',
'guesses|hunch',
'guff|jive',
'guff|nonsense',
'gum up|isportit',
'gutsy|brave,full of energy',
'halyavschik|deadbeat',
'handbag|vanity bag',
'handle|miss the bus',
'handsome|dreamboat,beautiful',
'hard work|grind',
'hardly|in a pigs eye',
'having sex|bang',
'head|top banana',
'heard that|whats up',
'hello',
'hero|action man',
'hide|elude',
'high audio|zing',
'highbrow|egghead',
'hole in the head|unwelcome',
'hooked|moonstruck',
'horn in|intervene',
'horse around|footle',
'hot air|babble',
'hot red|clear,cool,important',
'hot stuff|sensational information',
'how are you|whats up',
'hunch|guesses',
'hungry ration|mexican breakfast',
'hunk|beautiful',
'hustle and bustle|vanity,shindy',
'hyperactivity|ball of fire',
'iffy|unclear,doubtful',
'illegitimate|bastard,bastard',
'important knob|big daddy,big boss',
'important|hot red',
'in a pigs eye|barely,hardly',
'in dispute|betcha,arguing',
'in order|just so',
'in shaky situation|out of a limb',
'in touch|write,keep contact',
'incorrect|all wet,wrong',
'inquisitive|nosy',
'institute|carry away,worry,trail',
'intellectual|long hair',
'intervene|horn in',
'irritation|fucking',
'isportit|gum up',
'it doest wash|contrive not converge',
'it is no go|do not go,vanity',
'it takes two to tango|you need the participation of both parties',
'jailbait|underage',
'jam|problem',
'jangle|zing',
'jerk|berk',
'jester|zany',
'jig|sex',
'jimmy woodser|single',
'jive|guff',
'joe blow|man',
'johny raw|rookie,novice',
'joke|kid',
'junk|wreck',
'just as soon|also,as well',
'just now|recently',
'just so|in order',
'keep contact|in touch',
'kick back|bribe,give to the paw',
'kicky|fashion,nutty,delicious',
'kid|joke',
'kiss ass|suck,oil',
'knockout|beautiful woman,beautiful girl',
'knotty|difficult,confusing',
'knut|fool',
'kook|madcap',
'larynx|voice box',
'lay an egg|fail',
'lead over the nose|string along',
'leery|suspicious,skeptical',
'leeway|punk out',
'legman|messenger',
'lemon|rubbishy,garbage',
'let down|fail',
'likely winner|snoo in',
'like|dig,love',
'live|zappy',
'long',
'long hair|intellectual,creative people',
'long work|grind',
'loudmouth|prattler',
'lousy|twopenny',
'love|dig,like',
'lowdown|truth',
'luck out|carry,be doomed',
'lucky break|luck',
'luck|lucky break',
'lumpy|unsuccessful',
'madcap|kook',
'mafia|mob',
'man|dude',
'man|fucker',
'man|joe blow',
'man|man',
'man|man,small,bro',
'man|zod',
'marijuana|bush,grass',
'meals|grub',
'messenger|legman',
'mexican breakfast|hungry ration',
'middle finger|finger wave',
'miffed|offended',
'miserly|penny pincher',
'miss the bus|handle',
'moaner|sorehead',
'mob|gang,mafia',
'money|mula',
'monkey business|dirty work',
'moonstruck|hooked',
'mop|blunder',
'mothers darling|wimp',
'move faster|move your ass',
'move your ass|move faster',
'move|shake a leg',
'muddle up|muzzy',
'muggins|nitwit',
'mula|money',
'munchies|chips,popcorn',
'muzzy|muddle up',
'nagger|xanthippe',
'namely|thats the ticket',
'negro|nigger',
'new|rookie',
'nigger|negro',
'nitwit|muggins',
'nit|sleaseball',
'no sweat|easy',
'no way|under any circumstances',
'nonsense|crap,garbage',
'nonsense|guff',
'nosy|curious,inquisitive',
'nothing|zip',
'novice|johny raw',
'nub|scope',
'nutty|kicky',
'nut|fool,eccentric,crazy',
'nut|use ones beam',
'nut|zany',
'obscene gesture|finger wave',
'off beat|unusual,outlandish',
'offended|miffed',
'off|well-to-do',
'oil|kiss ass',
'ok|thumbs up',
'old hat|fusty',
'old history|old stuff',
'old stuff|old history',
'on the dry|dropped drink',
'optimistic|upbeat',
'out of a limb|in shaky situation',
'outlandish|off beat',
'pack of lies|all lies',
'pal|bro',
'pan out|pan',
'pan|pan out',
'partial|uptigh',
'party|tea-party',
'pass the back|dump the responsibility',
'penis|cock',
'penny pincher|miserly',
'perfuse|bullshit',
'period|fella',
'pipsqueak|piss-ant',
'piss off|bully,get,bored to the limit',
'piss-ant|whiffet,pipsqueak',
'plastic money|plastic',
'plastic|plastic money,credit card',
'playboy|tough cat',
'police|cop',
'poo|faeces,stool',
'popcorn|munchies',
'prattler|loudmouth',
'pregnant|bang-up',
'private|g.i.',
'problem|jam',
'prosperous|well-to-do',
'prostitute|call girl',
'prostitute|working girl',
'psycho|creep',
'puke|throw up',
'punk out|leeway',
'punk|sucker',
'pussycat|sweet girl',
'queer beggar|strange people',
'queer fish|freak',
'quick fix|tackling',
'quitter|defeatist,coward',
'rack ones brain|brain strain',
'rag|dumb bunny',
'raise hell|raise noise,arrange scandal',
'raise noise|raise hell',
'randan|tea-party',
'rattle off|rell off',
'ready|bingo',
'recently|just now',
'red tape|bureaucrats,bureaucratic red tape',
'rell off|rattle off',
'resentful person|sorehead',
'return|back up,go back',
'rich|well-to-do',
'rolling stone|vagrant',
'rookie|johny raw',
'rookie|new',
'rotten|ugly,bad',
'rot|eat avay',
'rubbishy|lemon',
's god|by golly',
'safe|earn ones wings',
'scam|fraud,deception',
'scapegoat|dumb bunny',
'scope|nub',
'security|well-to-do',
'sensational information|hot stuff',
'sex|cat',
'sex|dig',
'sex|jig',
'shag|to fuck',
'shake a leg|move',
'shindy|hustle and bustle',
'sick sheep|bad egg',
'single|jimmy woodser',
'sissy|crybaby',
'skeptical|leery',
'sleaseball|bastard,nit',
'slight advantage|edge out',
'slip ones trolley|go bananas',
'slob|sloven,grub',
'sloven|slob',
'slow|ease up',
'smak|zest',
'small|dude',
'small|man',
'smart|snazzy',
'snazzy|smart,trendy',
'snoo in|likely winner',
'snoop around|snoop',
'snoop|snoop around',
'so long|long,chao,hello,to meet',
'soak|crack a joke,unpin',
'sorehead|resentful person,moaner',
'speak slowly|back off,talk quieter',
'squalid|tacky',
'stalemate|up the tree',
'stool|poo',
'stop lying|come off it,good shoot the breeze',
'strange people|queer beggar',
'string along|lead over the nose,footle',
'strung|uptigh',
'stupid|airhead,goofy person',
'stupid|goofy',
'sucker|punk',
'suck|kiss ass',
'super|zero cool',
'surprise|gee',
'suspicious|leery',
'sweet girl|pussycat',
'tackling|quick fix',
'tacky|squalid',
'take a blunder|goof up',
'take ones words|eat his words',
'talk quieter|back off,speak slowly',
'tea-party|randan,party',
'thats it|you said it',
'thats the ticket|namely,thing',
'thing|thats the ticket',
'throat|voice box',
'throw up|puke',
'thumbs up|ok',
'times plyunut|duck soup,case',
'tipsy|cups',
'tits|breasts',
'to do something|act up',
'to fuck|shag',
'to meet',
'top banana|boss,head,cone,chief',
'tough cat|playboy,casanova',
'trail|carry away,institute,worry',
'trendy|snazzy',
'truth|lowdown',
'try to please|cozy up,adapt',
'twenty-five cents|two bits',
'twist around|distort',
'two bits|twenty-five cents,dollar quarter',
'twopenny|lousy',
'ubegat|elude',
'ugly|rotten',
'unclear|iffy',
'under any circumstances|no way',
'underage|jailbait',
'unpin|crack a joke,soak',
'unsuccessful|lumpy',
'unusual|off beat',
'unwelcome|hole in the head',
'up the tree|stalemate',
'upbeat|optimistic',
'uptight|strung,excited,partial',
'use ones beam|nut',
'vagrant|rolling stone',
'vanity bag|handbag',
'vanity|hustle and bustle',
'vanity|it is no go',
'victory|edge out',
'vigorous|zappy',
'voice box|throat,larynx',
'wacko|crazy man',
'well-to-do|rich,prosperous,security,off',
'whale away|beat',
'whats up|heard that,how are you,are you doing',
'whiffet|piss-ant',
'wimp|mothers darling',
'wooden|bonehead,goofy',
'working girl|prostitute',
'worry|carry away,institute,trail',
'wrap|end,finish',
'wreck|junk',
'write a few words|drop a line,drop a line',
'write|in touch',
'wrong|all wet,incorrect',
'xanthippe|nagger',
'xanthons|yellow',
'xmas|christmas',
'yak|chatter',
'yap|bigmouth,bitch',
'yellow|cowardly',
'yellow|xanthons',
'you need the participation of both parties|it takes two to tango',
'you said it|thats it',
'zany|jester,nut,fool',
'zappy|vigorous,live',
'zero cool|good,super',
'zero|zip',
'zest|smak,fun',
'zing|high audio,jangle',
'zip|zero,nothing',
'zod|fool,man',
'zymotic|zarazny'
);
				for ($i=0;$i<count($f);$i++)
				{
				$a = explode("|",$f[$i]);
				$b = explode(",",$a[1]);
				mt_srand((double)microtime()*1000000);
				$n = mt_rand(0,(count($b)-1));

				$b[$n] = trim($b[$n]);
                $a[0] = trim($a[0]);

//$b[0] = '##11'.$b[0].'##22';
$b[0] = '<font color="#1059C4">'.$b[0].'</font>';

				$cnt = str_replace(" ".$a[0]." "," ".$b[0]." ",$cnt);
				$cnt = str_replace(" ".$a[0].","," ".$b[0].",",$cnt);
				$cnt = str_replace(" ".$a[0]."."," ".$b[0].".",$cnt);
				$cnt = str_replace(" ".$a[0].";"," ".$b[0].";",$cnt);
				$cnt = str_replace(" ".$a[0].":"," ".$b[0].":",$cnt);
				$cnt = str_replace("(".$a[0]." ","(".$b[0]." ",$cnt);
				$cnt = str_replace("(".$a[0].",","(".$b[0].",",$cnt);
				$cnt = str_replace(" ".$a[0].")"," ".$b[0].")",$cnt);
				}
				Return $cnt;
			}


?>

