
<?php

function sokrasheniya($cnt)
			{
$f = array(
'Able-Bodied|AB',
'Academy|a.',
'access|Xs',
'acquired immune deficiency syndrome|AIDS',
'acre|a.',
'ad|Anno Domini',
'African National Congress|ANC',
'afternoon|a.',
'aids|Acquired Immune Deficiency Syndrome',
'Alabama|ALA',
'Algeria|Ag.',
'alternating current|AC',
'am not, are not|aint',
'American Army|AA',
'america|a.',
'ampere hour|ah',
'ancient|anc.',
'anc|African National Congress',
'Anglo - Saxon|AS',
'anno domini|AD',
'Annual return|Ar.',
'ante meridiem|am',
'appendix|Appx.',
'april|Apr.',
'archbishop|Abr.',
'Argentum|Ag.',
'arizona|Ariz.',
'arkansas|Ark.',
'Assistant|Asst.',
'Associated Press|AP',
'Association of Tennis Professionals|ATP',
'association|Assoc.',
'atmosphere|At.',
'Attachment|At.',
'Attention|At.',
'august|Aug.',
'author|a.',
'avenue|Ave.',
'Bachelor of Arts|BA',
'Bachelor of Medicine|BM',
'bachelor of science|B. Sc.',
'bachelor|B',
'Bahrain|Ba.',
'Bank of England|B. of E.',
'bank of england|BE',
'banknote|Bn.',
'bank|b.',
'Baronet|Bt.',
'BBC|British Broadcasting Corporation',
'Before Christ|BC',
'Before the Common Era|BCE',
'beryllium|Be',
'bet you|Betcha',
'big|b',
'bill of sale|BS',
'biological value|BV',
'Birthday|Bd.',
'Black & White|BW',
'black|b',
'blue|b',
'book|b',
'born|b',
'botanical|bot.',
'boulevard|Blvd.',
'brasil|BR',
'british academy|BA',
'british broadcasting corporation|BBC',
'British |B',
'british|B',
'Bulgaria|Bul.',
'bushel|bsh.',
'buzzing|zzz',
'Cable News Network|CNN',
'california|Cal.',
'canada|Can.',
'capacity|ñ.',
'Captain|Capt.',
'Cash Credit|CÑ',
'cash on delivery|COD',
'center|IC',
'centigrade|Ñ.',
'centimeter|ñ.',
'centimetre|cm.',
'Central Intelligence Agency|CIA',
'Chapter|Chap.',
'chief justice|CJ',
'Christmas Day|XD',
'christ|x.',
'church of england|CE',
'CIA|Central Intelligence Agency',
'cid|Criminal Investigation Department',
'Civil Defense|CD',
'civil service|CS',
'cnn|Cable News Network',
'college|ñ.',
'Colonel|Col.',
'colorado|Colo.',
'come on|Cmon',
'commander in chief|C.-in-C.',
'communist|Com.',
'compact disk|CD',
'compare|cp.',
'confer|cf.',
'Connecticut|Ñonn.',
'copper|Cu.',
'copyright|ñ.',
'corporation |ñ.',
'corporation|ñ.',
'Court Marshal|CM',
'creditor|cr.',
'criminal investigation department|CID',
'cross|x.',
'Cuba|Cu.',
'cubic|Cu.',
'cuprum|Cu.',
'Danger Zone|DZ',
'database server|DS',
'database|Db.',
'data|d.',
'date|d.',
'day of week|DoW',
'day|d.',
'dead|d.',
'deep purple|DP',
'degree|d.',
'degree|deg.',
'delaware|Del.',
'democratic party|DP',
'democratic|D.',
'democrat|D.',
'denarius|d.',
'denmark|Da.',
'department of defense|DoD',
'Department of Health|DH',
'Depth|Dp.',
'Deutsche Bank|DB',
'deutsch|De',
'development plan|DP',
'Diego Armando Maradona|DAM',
'diesel fuel|DF',
'Digital Photography|DP',
'digital video|DV',
'digital zoom|DZ',
'Director General|DG',
'disneyland|Dl',
'district attorney|DA',
'district of columbia|DC',
'Doctor|Dr.',
'domain name|DN',
'dominica|Dm',
'Dominica|Do.',
'double|Db.',
'downhill|DH',
'Download|Dl',
'Down|Dn.',
'dozen|Dz.',
'dreamweaver|Dw',
'drive|Dr.',
'Dubai|Du.',
'dunno|Du.',
'dutch|Du.',
'each|ea',
'east-west|EW',
'Easy|ez.',
'economic development|ED',
'Economy|Ec.',
'Ecuador|EC',
'Edit|Ed.',
'education international|EI',
'Education|Ed.',
'education|Edu.',
'Electric Field|EF',
'electrocardiography|EKG',
'electronic arts|EA',
'Electronic Commerce|EC',
'elementary school|ES',
'elementary|El.',
'element|El.',
'elvis presley|EP',
'encyclopedia britannica|EB',
'Enemy|En.',
'engineer|En.',
'England and Wales|EW',
'English|Eng.',
'Equatorial Guine|EKG',
'eritrea|Er.',
'error|er.',
'Esperanto|Eo.',
'Estonia|Es.',
'et cetera|etc.',
'European Economic Community|EEC',
'european free trade association|EFTA',
'European Parliament|EP',
'European Union|EU',
'euro|EU',
'Event horizon|EH',
'Every Day|ED',
'exempli gratia|eg',
'eye contact|EC',
'fahrenheit|F.',
'Family Tree|FT',
'Family Video|FV',
'fan club|FC',
'Farsi|Far.',
'february|f.',
'february|f. ôåâðàëü',
'Federal Bureau of Investigation|FBI',
'Feed|FD',
'fellow|f.',
'female|fem',
'feminine|fem',
'Fifth Wheel|FW',
'fiji|Fj.',
'file transfer protocol|FTP',
'Filter|Fl.',
'Finance Director|Fd.',
'Financial Aid|FA',
'Finish Line|FL',
'Finland|Fi.',
'Finnish|Fi.',
'fire department|Fd.',
'firewall|fw.',
'First Aid|FA',
'flat|Fl.',
'florida|Fl.',
'Football Association|FA',
'football club|FC',
'foreign language|FL',
'foreign minister|FM',
'Forget It|FI',
'format|fm.',
'forward|fw.',
'france|Fr.',
'franch|fr.',
'freeware|fw.',
'freezing point|FP',
'french kiss|FK',
'french|f.',
'frequently asked question|FAQ',
'Fresh Water|FW',
'friday|f.',
'friend|Fd.',
'from |fm.',
'from|fm.',
'full time|FT',
'gallon|gal.',
'gambia|Gm.',
'game over|GO',
'gamma rays|GR',
'gateway|GW',
'General Manager|GM',
'general motors|GM',
'general|g.',
'George Washington|GW',
'Georgia|Ga.',
'germany|Gm.',
'german|De',
'german|Ger.',
'give me|Gimme',
'Global Warming|GW',
'going to|',
'going to||Go.',
'gold medal|GM',
'gonna|Go.',
'Good Day|GD',
'Good Job|GJ',
'good luck all|GLA',
'good luck|GL',
'Good Morning|GM',
'good night|GN',
'Good|Gd.',
'got you|Go.',
'gothic|Go.',
'Gotta|Go.',
'grade|Gd.',
'gramme|g.',
'gram|g.',
'Gram|Gr.',
'Great Britain|GB',
'Greek|Gk.',
'green zone|GZ',
'greenland|Gl.',
'greenwich mean time|GMT',
'green|g.',
'Ground Zero|Gz.',
'ground|Gd.',
'group of 8|G8',
'Guam|Gu.',
'guaranteed|Gtd.',
'Guinea|Gn.',
'Guinea|Gv.',
'happy birthday|HB',
'harbor|h.',
'hard disk|HD',
'Harley-Davidson|Hd.',
'health insurance|HI',
'heavy metal|HM',
'hectare|ha.',
'height|h.',
'hemoglobin|hb.',
'high pressure|HP',
'highway|hwy',
'honda|Hd.',
'horsepower|h. p.',
'hour|h.',
'House of Lords|H. L.',
'Hundred |Hd',
'hundred|h.',
'hundred|Hd',
'Hungary|Hu.',
'hypertext transfer protocol|HTTP',
'Hyundai|Hd.',
'I Want You|IWU',
'ibidem|ib.',
'ibidem|ibid.',
'ice cream|IC',
'Iceland|Ic.',
'id est|ie',
'identification data|ID',
'illinois|Ill.',
'In My Humble Opinion|IMHO',
'include|incl.',
'Income Tax|IT',
'indiana|Ind.',
'India|I.',
'Indonesia|Id.',
'Information|i.',
'Instant|Inst.',
'international atomic energy agency|IAEA',
'international|i.',
'Internet|i.',
'iowa|Ia.',
'island|i.',
'jack|j.',
'Jamaica|Ja.',
'Japan Tobacco|JT',
'japan|Ja.',
'journal|j.',
'Judge|J.',
'Junior League|JL',
'junior|jr.',
'just|j.',
'kentucky|Ky.',
'Kilobit|Kb.',
'KiloByte |Kb.',
'kilobyte|Kb.',
'kilometer|km.',
'king|K.',
'Kiss Me|KM',
'knight|Kt.',
'knock-out|KO',
'Koninklijke Luchtvaart Maatschappij|KLM',
'ku-klux-klan|KKK',
'lady|l.',
'lake|l.',
'land rover|LR',
'last name|LN',
'latin|l.',
'latitude|lat.',
'League of Arab State|LAS',
'lebanon|Lb.',
'left|l.',
'let me|Lemme',
'let you|Letcha',
'letter of commitment|LOC',
'liberia|Lr.',
'library of congress|LC',
'library|Lib.',
'libra|l.',
'Light Weight|LW',
'limited|Ld.',
'limited|Ltd.',
'Lincoln|Ln.',
'line|Ln.',
'living room|LR',
'lot of|Lotta',
'lots of|Lotsa',
'Louisiana|La',
'luxembourg|Lu.',
'maine|Me.',
'malawi|Mw.',
'Manchester United|MU',
'market value|MV',
'Maryland|Md.',
'masculine|m.',
'massachusetts|Ma.',
'maximum permitted låvel|MPL',
'megabit|Mb.',
'megabyte|Mb.',
'member of parliament|MP',
'Mercedes-Benz|MB',
'meter|m.',
'michigan|Mich.',
'Microsoft Windows|MW',
'microsoft word|MW',
'miles per hour|mph',
'mile|m.',
'military police|MP',
'millimeter|mm.',
'Minnesota|Minn.',
'minute|m.',
'mississippi|Miss.',
'missouri|Mo.',
'Montana|Mont.',
'Morocco|Mo.',
'most probable number|MPN',
'national basketball association|NBA',
'national football league|NFL',
'National Hockey League|NHL',
'national league|NL',
'Nebraska|Neb.',
'netherlands|Nl.',
'neuter|n.',
'neutral|n.',
'Nevada|Nev.',
'new hampshire|NH',
'new jersey|NJ',
'New Mexico|N. Mex.',
'new york|NY',
'nicaragua|Nu.',
'nice hand|nh',
'No Problem|NP',
'nobel prize|NP',
'North America|NA',
'north atlantic treaty organization|NATO',
'north carolina|NC',
'north dakota|N. Dak.',
'north pole|NP',
'North|N.',
'nota bene|NB',
'noun|n.',
'november|n.',
'number|n.',
'Office Manager|OM',
'officer|o.',
'officer|Of.',
'official|o.',
'Ohio|Oh.',
'Oklahoma|Okla.',
'old english|OE',
'old french|OF',
'Old Style|OS',
'olive oil|OO',
'oman|Mu.',
'oman|Om.',
'On-Line|OL',
'ontario|On.',
'operating system|OS',
'opinion|op.',
'oregon|Oreg.',
'organization|o.',
'out of|outa',
'overweight|ow.',
'page|p.',
'Panzer|Pz.',
'paragraph|par.',
'partner|p.',
'password|pw.',
'pennsylvania|Penn.',
'Pennsylvania|Penna.',
'people|ppl',
'per cent|p. c.',
'per pro|pp',
'per week|PW',
'Periodic Table of Elements|PTE',
'please turn over|PTO',
'plural|pl.',
'plutonium|Pu.',
'political|pol.',
'port|p.',
'post meridiem|pm',
'postscript|PS',
'preface|pref.',
'Prime Minister|PM',
'Private|Pte.',
'professor|Prof.',
'program|p.',
'Proverbs|Pv.',
'Quality Factor|QF',
'quality|q.',
'quarter|q.',
'quarter|qr.',
'quebec|Que.',
'queen|q.',
'question|q.',
'quick fix|QF',
'Radio Liberty|RL',
'radioactive material|RAM',
'random number|RN',
'random-access memory|RAM',
'Real Estate|RE',
'real media|RM',
'red cross|RC',
'red wine|RW',
'red|r.',
'republic of bulgaria|RB',
'rewritable|RW',
'right|r.',
'river|r.',
'road|rd.',
'room|rm.',
'Russian Federation|RF',
'russian|r.',
'russian|Ru',
'russia|Ru',
'Rwanda|Rw.',
'saint|St.',
'saturday|Sat.',
'saudi arabia|SA',
'search engine optimization|SEO',
'second|s.',
'senior|Sr.',
'sex|s.',
'sex|s. ïîë',
'shilling|s.',
'sign|s.',
'small business|SB',
'somebody|smb.',
'south africa|SA',
'South America|SA',
'south carolina|SC',
'south dakota|SD',
'south-east|SE',
'south-east|SE þãî-âîñòîê',
'south-west|SW',
'south|s.',
'soviet union|SU',
'spain|ES',
'Special Safeguard|SSG',
'street|St.',
'sudan|Su.',
'sukhoi|SU',
'Tank|T',
'tanzania|Tz.',
'team leader|TL',
'telephone|t.',
'Television|TV',
'temperature|t.',
'tennessee|Tenn.',
'ten|T',
'terabyte|Tb.',
'test drive|TD',
'thailand|Th.',
'thank god|TG',
'theater|Th.',
'thursday|Th.',
'time|t.',
'today|Td.',
'togo|Tg.',
'Toilet|Tl.',
'ton|t.',
'top secret|TS',
'town|t.',
'Transmission Control Protocol|TCP',
'tropical storm|TS',
'tuberculosis|Tb.',
'tupolev|TU',
'Ukraine|Ua',
'ultraviolet|uv',
'union|u.',
'United Kingdom|UK',
'United Nations Educational, Scientific and Cultural Organization|UNESCO',
'united nations|UN',
'united states army|USA',
'united states of america|USA',
'united states ship|USS',
'United States|US',
'united|u.',
'university|u.',
'unlimited|ul.',
'upper|u.',
'user name|UN',
'Uzbekistan|Uz.',
'valentines day|VD',
'valuable cargo|VC',
'Value Added Tax|VAT',
'verb|vb.',
'vermont|Vt.',
'verse|vs.',
'version|v.',
'versus|vs',
'very bad|VB',
'very good|vg',
'very nice hand|vnh',
'very well|VW',
'video|v.',
'Vietnam War|VW',
'vietnam|VM',
'Virginia|Va.',
'virtual memory|VM',
'voice mail|VM',
'voice of america|VOA',
'Volkswagen|VW',
'volleyball|VB',
'voltage|VL',
'volvo|VV',
'Waiting List|WL',
'wall|Wl.',
'want to|Wanna',
'Washington|Wa.',
'watt|w.',
'weather|We.',
'web|w.',
'wednesday|w.',
'wednesday|We.',
'week ending|WE',
'week|wk.',
'weight|w.',
'western union|WU',
'west|w.',
'what women want|WWW',
'wheel|Wl.',
'white|w.',
'width|w.',
'wisconsin|Wis.',
'with|w.',
'world health organization|WHO',
'World League|WL',
'world trade organization|WTO',
'world wide web|WWW',
'wyoming|Wyo.',
'xenon|Xe',
'xerox|x.',
'year|a.',
'yemen|Ym',
'You are Welcome|YW',
'younger|Yr.',
'your friend|YF',
'your mom|YM',
'zambia|Za.',
'Zambia|Zm.',
'zero|z.',
'zimbabwe|Zw.',
'zirconium|Zr.',
'zodiac|z.',
'zone|z.',
'zone|Zn.',
'ñompany|Co.',
'ñountry|Co',
'ñounty|Co'
);
				for ($i=0;$i<count($f);$i++)
				{
				$a = explode("|",$f[$i]);
				$b = explode(",",$a[1]);
				mt_srand((double)microtime()*1000000);
				$n = mt_rand(0,(count($b)-1));

				$b[$n] = trim($b[$n]);
                $a[0] = trim($a[0]);

//$b[0] = '##11'.$b[0].'##22';
$b[0] = '<font color="#1059C4">'.$b[0].'</font>';

				$cnt = str_replace(" ".$a[0]." "," ".$b[0]." ",$cnt);
				$cnt = str_replace(" ".$a[0].","," ".$b[0].",",$cnt);
				$cnt = str_replace(" ".$a[0]."."," ".$b[0].".",$cnt);
				$cnt = str_replace(" ".$a[0].";"," ".$b[0].";",$cnt);
				$cnt = str_replace(" ".$a[0].":"," ".$b[0].":",$cnt);
				$cnt = str_replace("(".$a[0]." ","(".$b[0]." ",$cnt);
				$cnt = str_replace("(".$a[0].",","(".$b[0].",",$cnt);
				$cnt = str_replace(" ".$a[0].")"," ".$b[0].")",$cnt);
				}
				Return $cnt;
			}


?>

